provider = "GitHub"
base_path = "streamlit"

[github]
repo = "github-org/gitops-repo"
base_branch = "main"
token = "github_pat_1234567890ABCDEFGHIJKLMNOpqrstuvwxyz"

[gitlab]
url = "https://gitlab.com"
project_id = "12345678"
base_branch = "main"
token = "glpat_1234567890ABCDEFGHIJKLMNOpqrstuvwxyz"

[harbor]
url = "https://your-harbor-instance.com"
project = "project-name-on-harbor"
username = "robot-account-username"
password = "robot-account-password"